services:
  menu_api:
    container_name: menu_api
    build:
      context: ./menu_api
      dockerfile: Dockerfile
    volumes:
      - ./menu_api:/menu_api
    env_file: ./menu_api/.env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
